name: ai4small
channels:
  - conda-forge
dependencies:
  - python=3.8.17
  - geopandas=0.12.2
  - rasterio=1.3.7
  - h5py=3.9.0
  - mlflow=2.7.1
  - pip
  - pip:
    - opencv-python==4.5.5.64
    - scikit-image==0.19.2
    - segmentation-models==1.0.1
    - tensorflow==2.8.0
    - chardet==5.1.0
    - earthengine-api==0.1.343
    - imagecodecs==2023.1.23
    - protobuf==3.20.2
    - keras-unet==0.1.2
    - StrEnum==0.4.15